config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :searches, only: [:new, :create, :update, :edit]
  resources :products, only: [:show, :create]
  resources :containers, only: [:index, :create, :new]

  get "/favorites", to: "searches#favorites"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/find", to: "containers#find"
  get '/find/result', to: "containers#result"
  get "/find/tip", to: "containers#tip"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/container.rb
class Container < ApplicationRecord

  # geocoded_by :address
  # after_validation :geocode, if: :will_save_change_to_address?
end

app/models/packaging.rb
class Packaging < ApplicationRecord
  has_many :product_packages

  def color_name
    if category == "metal" || category == "carton" || category == "plastique"
      "jaune"
    else
      "gray"
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_packages, dependent: :destroy
  has_many :searches, dependent: :destroy
  has_one_attached :photo
  # validates :upc, uniqueness: true

  def color_name
    all_packagings_colors = []
    product_packages.each do |product_package|
      all_packagings_colors << product_package.packaging.color_name
    end
    unique_colors = all_packagings_colors.uniq
    if unique_colors.count == 1
      return unique_colors[0]
    else
      "neutral"
    end
  end
end

app/models/product_package.rb
class ProductPackage < ApplicationRecord
  belongs_to :product
  belongs_to :packaging

  def color_name
    packaging.color_name
  end
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :searches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  CARTON = ["carton", "paquet"]
  GLASS  = ["verre", "glass", "bocal"]
  METAL = ["aluminum", "metal", "conserve", "métal"]
  PLASTIC = ["plastique", "plastic", "sachet"]

  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @containers = Container.where(material: "verre")
    @markers = @containers.map do |container|
      {
        lat: container.latitude,
        lng: container.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { container: container }),
        image_url: helpers.asset_url('green-point.svg')
      }
    end
  end

  def create
  end

  def result
    @containers = Container.where("lower(material) LIKE lower(?)", "pile")
    @markers = @containers.map do |container|
      {
        lat: container.latitude,
        lng: container.longitude,
        infoWindow: render_to_string(partial: "info_window_pile", locals: { container: container }),
        image_url: helpers.asset_url('blue-point.svg')
      }
    end
  end

  def tip
    if params[:search]
      @search_results = params[:search]
      respond_to do |format|
        format.js { render partial: 'search-results'}
      end
    else
      "No results"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/products_controller.rb
require 'httparty'
require 'json'

class ProductsController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @product = Product.find(params[:id])
  end
# dodo la sardine 3263670162219
# stir fry doudou 737628064502
# chips : 5060042640515
# pitch choco : 3256540000636
# evian : 3068320120256

  def create
    @product = Product.new(product_params)
    if Product.find_by(upc: "#{product_params[:upc]}")
      @product = Product.find_by(upc: "#{product_params[:upc]}")
      @search = Search.find_by(product: @product)
      if @search.nil?
        @search = Search.new(product: @product, user: current_user)
        # raise
        @search.save
      else
        @search
      end
      # redirect_to product_path(@product)
    else
      @search = Search.new
      @search.user = current_user
      response = OpenfoodfactsService.new(product_params[:upc]).call
      if response.parsed_response["status_verbose"] == "product not found"
        render "searches/new"
      else
        @product.title = response["product"]["product_name"]
        @product.brand = response["product"]["brands"]

        @package = response["product"]["packaging"]
        package_array = @package.downcase.gsub(",", " ").split(" ").uniq
        package_array.map! do |item|
          if CARTON.include?(item)
            item = "carton"
          elsif GLASS.include?(item)
            item = "verre"
          elsif METAL.include?(item)
            item = "metal"
          elsif PLASTIC.include?(item)
            item = "plastique"
          else
            item = "undefined"
          end
        end

        clean_result = package_array.reject { |x| x == "undefined" }
        @product.package_array = clean_result.uniq
        @product.save
        @search.product = @product
        @search.save

        @product.package_array.each do |item|
          product_package = ProductPackage.create!(product: @product, packaging: Packaging.find_by(category: item))
        end
        # redirect_to product_path(@product)
      end
    end
    render json: {
      product: @product,
      modal_html: render_to_string(partial: "searches/scan_result")
    }
  end

  private

  def product_params
    params.require(:product).permit(:upc, :photo)
  end

  def url(upc)
    response = HTTParty.get('https://world.openfoodfacts.org/api/v0/product/#{upc}.json')
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    @search = Search.new
    @product = Product.new
  end

  def create

  end

  def favorites
    @favorites = Search.where(favorite: true)
  end

  def edit
    @search = Search.find(params[:id])
    @user = current_user
    @product = Product.find(params[:product_id])
    # authorize @lama
  end

  def update
    @search = Search.find(params[:id])
    @favorite = @search.favorite ? false : true
    if @search.update(favorite: @favorite)
      respond_to do |format|
        format.html { redirect_to favorites_path }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'products/show' }
        format.js  # <-- idem
      end
    end
  end

  private

  def product_params
    params.require(:product).permit(:upc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/containers/_info_window.html.erb
<div class="markers_infos">
  <h2>Conteneur de verre</h2>
  <p><%= container.address.downcase %>, <%= container.sector.downcase.capitalize %></p>
</div>

app/views/containers/_info_window_pile.html.erb
<div class="markers_infos">
  <h2><%= container.name.downcase.capitalize %></h2>
  <p><%= container.address %></p>
  <p><%= container.hours %></p>
</div>

app/views/containers/_search-results.js.erb
function displayResult(innerHTML) {

  const result = document.querySelector(".search-results");
  result.innerHTML = innerHTML;

}

displayResult('<%= j render "containers/tips" %> ');

app/views/containers/_tips.html.erb
<div class="results-content">
  <h2> Piles </h2>
    <div class="sorting-card">
      <div class="blue">
        <div class="category">
          <p><i class="fas fa-lightbulb", style="color: #3f96c1">&nbsp;</i>Consigne de tri : à déposer dans les points de collecte (petites et grandes surfaces) équipés de bornes spécifiques.</p>
        </div>
        <div class=button-glass>
          <div class="find-container-btn"><i class='fas fa-map-marker-alt', style="color: white"></i> <%= link_to "Trouver un point de collecte".html_safe, find_result_path %></div>
        </div>
      </div>
    </div>
</div>

app/views/containers/find.html.erb
<div class="container question">
  <h1>Que voulez-vous trier ?</h1>
  <br>
  <div class="p-1 bg-light rounded rounded-pill shadow-sm mb-4">
    <%= form_tag(find_tip_path, method: "get", class: "input-group", remote: true) do %>
    <%= text_field_tag(:search, params[:search], placeholder: "Entrer un objet à trier", class: "form-control border-0 bg-light") %>
      <div class="input-group-append">
        <%#= submit_tag 'Rec', class: "btn btn-link text-success" do %>
          <!-- <i class="fa fa-search"></i> -->
        <%# end %>
        <%= button_tag(type: "submit", class: "btn btn-link text-success") do %>
          <%#= submit_tag 'Recherche', class: "btn btn-link text-success" %>
          <i class="fa fa-search"></i>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="search-results">
  </div>
</div>

app/views/containers/index.html.erb
<div
  id="map"
  style="width: 100%;
  height: 780px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/containers/result.html.erb
<div
  id="map"
  style="width: 100%;
  height: 780px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable"  content="yes">
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <title><%= meta_title %></title>
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <div class="sticky-footer <%= current_page?(root_path) ? "without-margin-bottom" : "" %> ">
    <%#= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
    <div class="bottom-navbar">
      <% if current_page?(new_search_path) %>
      <%= render 'shared/bottom-bar-scan' %>
      <% else %>
      <%= render 'shared/bottom-bar' %>
      <% end  %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-home">

    <div class="image_buddies">
      <h1>Ben vous aide à trouver la poubelle qu'il faut !</h1>
      <%= image_tag "group-6.svg", alt: "Poubelles" %>
    </div>
  </div>
</div>
<%#= link_to "Sign out", destroy_user_session_path, :method => :delete %>

app/views/products/show.html.erb
<div class="container">
  <!-- <h2 class="localisation">Je trie à &nbsp;<i class="fas fa-map-marked-alt"></i> &nbsp; Paris 11ème </h2> -->
  <div class="product-card d-flex justify-content-between">
    <div class="product-details">
      <h3><%= @product.title.downcase.capitalize %></h3>
      <p><%= @product.brand %></p>
    </div>
    <div class="add-favorites ml-3">
      <% @product.searches.each do |search| %>
        <div class="favorite-btn mt-1" data-star="<%= search.id %>">
          <%= render 'searches/yellow_star', search: search %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="results-content">
    <% @product.product_packages.each do |item| %>
      <div class="sorting-card">
        <% if item.packaging.category == "verre" %>
          <div class="gray">
            <div class="category">
              <h3> <%= item.packaging.category.capitalize %></h3>
            <p><%= item.packaging.instruction %></p>
            <p class="tip"><i class="fas fa-lightbulb", style="color: #B8B8B5">&nbsp;</i><%= item.packaging.tip %></p>
            </div>
              <div class="image-glass"><%= image_tag "GroupVerre.svg", class: "glass_bin" %></div>
            <div class=button-glass>
              <div class="current-position-btn"><i class='fas fa-map-marker-alt', style="color: white"></i> <%= link_to "Trouver un conteneur verre ".html_safe, containers_path %></div>
            </div>
          </div>
        <% else %>
          <div class="yellow">
            <div class="category">
              <h3> <%= item.packaging.category.capitalize %></h3>
            <p><%= item.packaging.instruction %></p>
            <p class="tip"><i class="fas fa-lightbulb", style="color: #FECB1D">&nbsp;</i><%= item.packaging.tip %></p>
            </div>
            <div class="image-bin"> <%= image_tag "GroupJaune.svg", class: "yellow_bin" %></div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/searches/_scan_result.html.erb
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="scan-result">
  <div class="modal-dialog-centered modal-sm">
    <div class="modal-window">
      <div class="modal-content">
        <% @product.product_packages.each do |product_package| %>
            <% if product_package.packaging.category == "verre" %>
            <div class="modal-header border-0">
              <h4 class="modal-title"><i class="fas fa-circle", style="color: #B8B8B5"></i>&nbsp;&nbsp;&nbsp;<%= product_package.packaging.category.capitalize %></h4>
            </div>
            <div class="modal-body">
              <%= product_package.packaging.instruction %>
            </div>
            <% elsif product_package.packaging.category == "metal" || product_package.packaging.category == "carton" || product_package.packaging.category == "plastique" %>
              <div class="modal-header border-0">
                <h4 class="modal-title"><i class="fas fa-circle", style="color: #FECB1D"></i>&nbsp;&nbsp;&nbsp;<%= product_package.packaging.category.capitalize %></h4>
              </div>
              <div class="modal-body">
                <%= product_package.packaging.instruction %>
              </div>
            <% end %>
          <% end %>
        <div class="modal-footer border-0">
          <%= link_to "Voir plus", product_path(@product), class: "button-modal" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/searches/_yellow_star.html.erb
<% if search.favorite %>
  <p id="fav" class="fav-btn"><%= link_to "<i class='fas fa-star fa-lg' style='color:#FECB1D;'></i>".html_safe, search_path(search), method: :patch, remote: true %></p>
<% else %>
  <p id="no_fav" class="fav-btn"><%= link_to "<i class='fas fa-star fa-lg' style='color:#A8A9AD;'></i>".html_safe, search_path(search), method: :patch, remote: true %></p>
<% end %>

app/views/searches/favorites.html.erb
<div class="container">
  <h1>Mes favoris</h1>
  <% @favorites.each do |favorite| %>
    <div class="card-favorite d-flex justify-content-between">
      <div class="favorite-text">
        <div class="card-border card-border-<%= favorite.product.color_name %>">
          <div class="favorite-title">
            <h2><%= link_to "#{favorite.product.title}", product_path(favorite.product) %></h2>
            <div class="favorite-btn" data-star="<%= favorite.id %>">
              <%= render 'searches/yellow_star', search: favorite %>
            </div>
          </div>
          <p><%= favorite.product.brand %></p>
          <% favorite.product.product_packages.each do |product_package| %>
            <p>
              <i class="fas fa-circle circle-<%= product_package.color_name %>"></i>
              <%= product_package.packaging.category.capitalize %> :
              <%= product_package.packaging.instruction %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/searches/new.html.erb
<div id="scan">
  <div class="panel-body">
    <div id="scandit-barcode-picker" data-api-key="<%= ENV["SCANDIT_KEY"] %>" style="max-width: 100vw; height: 100vh;"></div>
  </div>
</div>


<div id="scan-result-modal-placeholder">
</div>


<input type="hidden" id="authenticity-token" value="<%= form_authenticity_token %>" />

app/views/searches/update.js.erb
function refreshStar(innerHTML) {

  const newStar = document.querySelector("[data-star='<%= @search.id %>']");
  newStar.innerHTML = innerHTML;

};

refreshStar('<%= j render "searches/yellow_star", search: @search %>');

app/views/shared/_bottom-bar-scan.html.erb
<div class="bottom-bar">
    <div class="bottom-bar-links">
      <div class="favorites">
        <%= link_to favorites_path do %>
          <%= image_tag "star-gray.svg", class: "favorite_btn"%>
        <% end %>
        <p>MES FAVORIS</p>
      </div>
      <div class="center">
        <%= image_tag "center-line.svg", class: "line"%>
      </div>
      <div class="search">
        <%= link_to find_path do %>
        <%= image_tag "loupe-gray.svg", class: "search_btn"%>
        <% end %>
        <p>RECHERCHE</p>
      </div>
  </div>

app/views/shared/_bottom-bar.erb
 <div class="bottom-bar">
    <div class="bottom-bar-links">
      <div><%= image_tag "002-favorites.svg", class: "favorite"%></div>
      <div class="code-bar_container">
        <div><%= image_tag "003-line.svg", class: "code-bar"%></div>
      </div>
      <div><%= image_tag "001-search.svg", class: "search"%></div>
    </div>
  </div>

app/views/shared/_bottom-bar.html.erb
<div class="bottom-bar">
    <div class="bottom-bar-links">
      <div class="favorites">
        <%= link_to favorites_path do %>
          <%= image_tag "star-gray.svg", class: "favorite_btn"%>
        <% end %>
        <p>MES FAVORIS</p>
      </div>
      <div class="code-bar_container">
        <div>
          <%= link_to new_search_path do %>
            <%= image_tag "code_barre.svg", class: "code-bar_btn" %>
          <% end %>

        </div>
      </div>
      <div class="search">
        <%= link_to find_path do %>
        <%= image_tag "loupe-gray.svg", class: "search_btn"%>
        <% end %>
        <p>RECHERCHE</p>
      </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>